type: 'worker'
network: 'unix'
host: '0.0.0.0'
port: 8080
worker:
  master_addr: 'localhost:8080'
  acquire_task_duration: '10s'
  heartbeat_duration: '5s'
  plugin:
    name: 'word-count'
    path: './plugin/word-count.so'
    enabled: true
s3_endpoint: 'localhost:38877'
task_bucket: 'map-reduce'
intermediate_bucket: 'intermediate'
intermediate_prefix: 'intermediate-'
result_bucket: 'reduced'
result_prefix: 'reduced-'