type: 'worker'
network: 'tcp4'
host: '0.0.0.0'
port: 8083
worker:
  master_address: 'localhost:8080'
  acquire_task_duration: '10s'
  heartbeat_duration: '25s'
  plugin:
    name: 'word-count'
    path: '/Volumes/SuenChunYu/Projects/Go/src/github.com/suenchunyu/map-reduce/plugin/word-count.so'
    enabled: true
access_key: 'minioadmin'
access_secret: 'minioadmin'
s3_endpoint: 'localhost:9000'
task_bucket: 'map-reduce'
intermediate_bucket: 'intermediate'
intermediate_prefix: 'intermediate-'
result_bucket: 'reduced'
result_prefix: 'reduced-'